// src/components/Footer.tsx
'use client';

import Image from 'next/image';
import styles from '@/styles/Footer.module.css';

export default function Footer() {
  return (
    <footer className={styles.siteFooter} role="contentinfo" aria-labelledby="footer-title">
      <div className={styles.footerContent}>
        <div className={styles.brand}>
          <Image
            className={styles.logo}
            src="/ufpi-seeklogo.png"
            alt="UFPI"
            width={96}
            height={135}
            priority={false}
            sizes="(max-width: 640px) 72px, 96px"
            unoptimized
          />
          <h2 id="footer-title" className={styles.title}>
            Universidade Federal do Piauí
          </h2>
        </div>

        <address className={styles.address}>
          <strong>Endereço:</strong> © 2025, Bairro Ininga – Teresina – PI • CEP: 64049-550
          <br />
          Campus Universitário Ministro Petrônio Portella – UFPI
        </address>
      </div>

      <div className={styles.footerBottom}>
        <small className={styles.copy}>
          &copy; {new Date().getFullYear()} UFPI — Todos os direitos reservados.
        </small>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<script setup lang="ts"></script>

<template>
  <footer class="site-footer">
    <div class="footer-content">
      <img class="logo-placeholder" src="../assets/ufpi-seeklogo.png" alt="UFPI logo" />
      <p class="address">
        <strong>Endereço:</strong> © 2025, Bairro Ininga – Teresina – PI • CEP: 64049‑550<br />
        Universidade Federal do Piauí – UFPI • Campus Universitário Ministro Petrônio Portella
      </p>
    </div>
  </footer>
</template>

<style scoped>
.site-footer {
  /* background: var(--color-primary-container, #4f768b); */
  color: var(--color-on-primary-container, #ffffff);
  padding: 2rem 1rem;
  font-size: 0.9rem;
}

.footer-content {
  max-width: 1024px;
  margin-inline: auto;
  display: flex;
  align-items: center;
  gap: 2rem;
  text-align: center;
  flex-wrap: wrap;
  justify-content: center;
}

.logo-placeholder {
  width: calc(64px * 1.5);
  height: calc(90px * 1.5);
  padding: 0.5rem;
  /* background: var(--color-on-primary-container, #ffffff); */
  color: var(--color-primary-container, #4f768b);
  display: grid;
  place-content: center;
  font-weight: 700;
  border-radius: 4px;
}

.address {
  line-height: 1.4;
  font-weight: 500;
}
</style>
